### ISSUE TITLE
Font-face styles stripped/broken

### ISSUE THREAD

**Issue by acketon** [bu-ist/bu-custom-css#1]
It looks like font-face style declarations are getting stripped during minification/validation. 

We found it when trying to include: 
http://www.bu.edu/cdn/fonts/#BentonSansComp-Bold

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Dakota Chichester** in **#wp-dev**. [View the logs :arrow_right:](https://buweb.slack.com/archives/wp-dev/p1453221736000846)

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Dakota Chichester** in **#wp-dev**. [View the logs :arrow_right:](https://buweb.slack.com/archives/wp-dev/p1453490336001028)

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1453735726000018)

**Comment by inderpreet99** [comment]
This was fixed in [BU Custom CSS 2.0.2](https://github.com/bu-ist/bu-custom-css/releases/tag/2.0.2). It has been deployed to CMS PROD. Thanks.
